func a(){
    let aa=2025;
    func c(){
        println(aa);
    }
    c()
}
class A{
    let AA=2026;
    public func c(){
        println(AA);
    }
}
main(){
    // a();
    // A().c();
    let x1:Int8=127;
    let x2:Int16=255;
    let y:String;
    y="仓颉编程语言"
    println("${x1}${x2}")//字符串的连接
    println(y)
    // let x = 2025;
    // println(x1)
    // println(x2)
    // println(x)
}